import { RetailerProduct, Retailer, StockStatus } from '../types';

interface MockProduct {
  name: string;
  category: string;
  variants: {
    retailer: Retailer;
    title: string;
    brand: string;
    size: string;
    price: number;
    stockStatus: StockStatus;
    productUrl: string;
    imageUrl: string;
  }[];
}

// Mock product database with realistic grocery items
export const mockProducts: MockProduct[] = [
  {
    name: 'eggs',
    category: 'dairy',
    variants: [
      {
        retailer: 'walmart',
        title: 'Great Value Large White Eggs',
        brand: 'Great Value',
        size: '12 count',
        price: 3.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walmart.com/eggs',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/A8C055?text=Eggs',
      },
      {
        retailer: 'walgreens',
        title: 'Eggland\'s Best Large Eggs',
        brand: 'Eggland\'s Best',
        size: '12 count',
        price: 5.49,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walgreens.com/eggs',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/A8C055?text=Eggs',
      },
      {
        retailer: 'marianos',
        title: 'Private Selection Organic Eggs',
        brand: 'Private Selection',
        size: '12 count',
        price: 4.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.marianos.com/eggs',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/A8C055?text=Eggs',
      },
      {
        retailer: 'costco',
        title: 'Kirkland Signature Cage Free Eggs',
        brand: 'Kirkland',
        size: '24 count',
        price: 6.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.costco.com/eggs',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/A8C055?text=Eggs',
      },
      {
        retailer: 'samsclub',
        title: 'Member\'s Mark Large White Eggs',
        brand: 'Member\'s Mark',
        size: '24 count',
        price: 7.49,
        stockStatus: 'in-stock',
        productUrl: 'https://www.samsclub.com/eggs',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/A8C055?text=Eggs',
      },
    ],
  },
  {
    name: 'milk',
    category: 'dairy',
    variants: [
      {
        retailer: 'walmart',
        title: 'Great Value Whole Milk',
        brand: 'Great Value',
        size: '1 gallon',
        price: 3.48,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walmart.com/milk',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/B5B3E1?text=Milk',
      },
      {
        retailer: 'walgreens',
        title: 'Horizon Organic Whole Milk',
        brand: 'Horizon',
        size: '1 gallon',
        price: 6.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walgreens.com/milk',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/B5B3E1?text=Milk',
      },
      {
        retailer: 'marianos',
        title: 'Organic Valley Whole Milk',
        brand: 'Organic Valley',
        size: '1 gallon',
        price: 7.49,
        stockStatus: 'in-stock',
        productUrl: 'https://www.marianos.com/milk',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/B5B3E1?text=Milk',
      },
      {
        retailer: 'costco',
        title: 'Kirkland Signature Organic Milk',
        brand: 'Kirkland',
        size: '2 gallon pack',
        price: 10.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.costco.com/milk',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/B5B3E1?text=Milk',
      },
      {
        retailer: 'samsclub',
        title: 'Member\'s Mark Whole Milk',
        brand: 'Member\'s Mark',
        size: '1 gallon',
        price: 3.89,
        stockStatus: 'in-stock',
        productUrl: 'https://www.samsclub.com/milk',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/B5B3E1?text=Milk',
      },
    ],
  },
  {
    name: 'bread',
    category: 'bakery',
    variants: [
      {
        retailer: 'walmart',
        title: 'Wonder Bread Classic White',
        brand: 'Wonder',
        size: '20 oz',
        price: 2.48,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walmart.com/bread',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/2D2D2D?text=Bread',
      },
      {
        retailer: 'walgreens',
        title: 'Nature\'s Own Wheat Bread',
        brand: 'Nature\'s Own',
        size: '20 oz',
        price: 3.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walgreens.com/bread',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/2D2D2D?text=Bread',
      },
      {
        retailer: 'marianos',
        title: 'Dave\'s Killer Bread Organic',
        brand: 'Dave\'s Killer Bread',
        size: '27 oz',
        price: 5.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.marianos.com/bread',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/2D2D2D?text=Bread',
      },
      {
        retailer: 'costco',
        title: 'Kirkland Signature Organic Bread 2-Pack',
        brand: 'Kirkland',
        size: '42 oz (2 pack)',
        price: 7.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.costco.com/bread',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/2D2D2D?text=Bread',
      },
      {
        retailer: 'samsclub',
        title: 'Member\'s Mark Honey Wheat Bread',
        brand: 'Member\'s Mark',
        size: '24 oz',
        price: 2.98,
        stockStatus: 'in-stock',
        productUrl: 'https://www.samsclub.com/bread',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/2D2D2D?text=Bread',
      },
    ],
  },
  {
    name: 'butter',
    category: 'dairy',
    variants: [
      {
        retailer: 'walmart',
        title: 'Great Value Salted Butter',
        brand: 'Great Value',
        size: '1 lb',
        price: 4.98,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walmart.com/butter',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/A8C055?text=Butter',
      },
      {
        retailer: 'walgreens',
        title: 'Land O\' Lakes Butter',
        brand: 'Land O\' Lakes',
        size: '1 lb',
        price: 6.49,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walgreens.com/butter',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/A8C055?text=Butter',
      },
      {
        retailer: 'marianos',
        title: 'Kerrygold Irish Butter',
        brand: 'Kerrygold',
        size: '8 oz',
        price: 4.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.marianos.com/butter',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/A8C055?text=Butter',
      },
      {
        retailer: 'costco',
        title: 'Kirkland Signature Salted Butter 4-Pack',
        brand: 'Kirkland',
        size: '4 lbs',
        price: 16.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.costco.com/butter',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/A8C055?text=Butter',
      },
      {
        retailer: 'samsclub',
        title: 'Member\'s Mark Unsalted Butter',
        brand: 'Member\'s Mark',
        size: '1 lb',
        price: 5.48,
        stockStatus: 'in-stock',
        productUrl: 'https://www.samsclub.com/butter',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/A8C055?text=Butter',
      },
    ],
  },
  {
    name: 'chicken breast',
    category: 'meat',
    variants: [
      {
        retailer: 'walmart',
        title: 'Fresh Boneless Skinless Chicken Breast',
        brand: 'Freshness Guaranteed',
        size: '2.5 lbs',
        price: 11.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walmart.com/chicken',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/2D2D2D?text=Chicken',
      },
      {
        retailer: 'walgreens',
        title: 'Organic Chicken Breast',
        brand: 'Simple Truth',
        size: '1 lb',
        price: 8.99,
        stockStatus: 'low-stock',
        productUrl: 'https://www.walgreens.com/chicken',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/2D2D2D?text=Chicken',
      },
      {
        retailer: 'marianos',
        title: 'Private Selection Chicken Breast',
        brand: 'Private Selection',
        size: '2 lbs',
        price: 13.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.marianos.com/chicken',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/2D2D2D?text=Chicken',
      },
      {
        retailer: 'costco',
        title: 'Kirkland Signature Organic Chicken Breast',
        brand: 'Kirkland',
        size: '6.5 lbs',
        price: 29.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.costco.com/chicken',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/2D2D2D?text=Chicken',
      },
      {
        retailer: 'samsclub',
        title: 'Member\'s Mark Chicken Breast',
        brand: 'Member\'s Mark',
        size: '5 lbs',
        price: 19.98,
        stockStatus: 'in-stock',
        productUrl: 'https://www.samsclub.com/chicken',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/2D2D2D?text=Chicken',
      },
    ],
  },
  {
    name: 'bananas',
    category: 'produce',
    variants: [
      {
        retailer: 'walmart',
        title: 'Fresh Bananas',
        brand: 'Dole',
        size: '3 lbs',
        price: 1.79,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walmart.com/bananas',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/F5A524?text=Bananas',
      },
      {
        retailer: 'walgreens',
        title: 'Organic Bananas',
        brand: 'Organic',
        size: '2 lbs',
        price: 1.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walgreens.com/bananas',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/F5A524?text=Bananas',
      },
      {
        retailer: 'marianos',
        title: 'Simple Truth Organic Bananas',
        brand: 'Simple Truth',
        size: '2.5 lbs',
        price: 2.49,
        stockStatus: 'in-stock',
        productUrl: 'https://www.marianos.com/bananas',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/F5A524?text=Bananas',
      },
      {
        retailer: 'costco',
        title: 'Fresh Bananas Bunch',
        brand: 'Dole',
        size: '3 lbs',
        price: 1.49,
        stockStatus: 'in-stock',
        productUrl: 'https://www.costco.com/bananas',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/F5A524?text=Bananas',
      },
      {
        retailer: 'samsclub',
        title: 'Fresh Organic Bananas',
        brand: 'Organic',
        size: '3 lbs',
        price: 2.28,
        stockStatus: 'in-stock',
        productUrl: 'https://www.samsclub.com/bananas',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/F5A524?text=Bananas',
      },
    ],
  },
  {
    name: 'apples',
    category: 'produce',
    variants: [
      {
        retailer: 'walmart',
        title: 'Gala Apples',
        brand: 'Fresh',
        size: '3 lbs',
        price: 3.98,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walmart.com/apples',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/E57373?text=Apples',
      },
      {
        retailer: 'walgreens',
        title: 'Honeycrisp Apples',
        brand: 'Fresh',
        size: '2 lbs',
        price: 4.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walgreens.com/apples',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/E57373?text=Apples',
      },
      {
        retailer: 'marianos',
        title: 'Organic Fuji Apples',
        brand: 'Simple Truth',
        size: '2 lbs',
        price: 5.49,
        stockStatus: 'in-stock',
        productUrl: 'https://www.marianos.com/apples',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/E57373?text=Apples',
      },
      {
        retailer: 'costco',
        title: 'Kirkland Signature Gala Apples',
        brand: 'Kirkland',
        size: '5 lbs',
        price: 6.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.costco.com/apples',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/E57373?text=Apples',
      },
      {
        retailer: 'samsclub',
        title: 'Fresh Gala Apples',
        brand: 'Fresh',
        size: '5 lbs',
        price: 7.48,
        stockStatus: 'in-stock',
        productUrl: 'https://www.samsclub.com/apples',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/E57373?text=Apples',
      },
    ],
  },
  {
    name: 'orange juice',
    category: 'beverages',
    variants: [
      {
        retailer: 'walmart',
        title: 'Tropicana Pure Premium Orange Juice',
        brand: 'Tropicana',
        size: '52 fl oz',
        price: 4.98,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walmart.com/oj',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/F5A524?text=OJ',
      },
      {
        retailer: 'walgreens',
        title: 'Simply Orange Juice',
        brand: 'Simply',
        size: '52 fl oz',
        price: 5.49,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walgreens.com/oj',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/F5A524?text=OJ',
      },
      {
        retailer: 'marianos',
        title: 'Simple Truth Organic Orange Juice',
        brand: 'Simple Truth',
        size: '52 fl oz',
        price: 6.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.marianos.com/oj',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/F5A524?text=OJ',
      },
      {
        retailer: 'costco',
        title: 'Kirkland Signature Orange Juice',
        brand: 'Kirkland',
        size: '2 x 59 fl oz',
        price: 9.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.costco.com/oj',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/F5A524?text=OJ',
      },
      {
        retailer: 'samsclub',
        title: 'Member\'s Mark Orange Juice',
        brand: 'Member\'s Mark',
        size: '89 fl oz',
        price: 6.98,
        stockStatus: 'in-stock',
        productUrl: 'https://www.samsclub.com/oj',
        imageUrl: 'https://placehold.co/200x200/F5C4B8/F5A524?text=OJ',
      },
    ],
  },
  {
    name: 'tide pods',
    category: 'household',
    variants: [
      {
        retailer: 'walmart',
        title: 'Tide PODS Liquid Laundry Detergent',
        brand: 'Tide',
        size: '72 count',
        price: 19.97,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walmart.com/tide',
        imageUrl: 'https://placehold.co/200x200/B5B3E1/2D2D2D?text=Tide',
      },
      {
        retailer: 'walgreens',
        title: 'Tide PODS Original Scent',
        brand: 'Tide',
        size: '42 count',
        price: 14.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walgreens.com/tide',
        imageUrl: 'https://placehold.co/200x200/B5B3E1/2D2D2D?text=Tide',
      },
      {
        retailer: 'marianos',
        title: 'Tide PODS Spring Meadow',
        brand: 'Tide',
        size: '81 count',
        price: 21.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.marianos.com/tide',
        imageUrl: 'https://placehold.co/200x200/B5B3E1/2D2D2D?text=Tide',
      },
      {
        retailer: 'costco',
        title: 'Tide PODS Laundry Detergent',
        brand: 'Tide',
        size: '152 count',
        price: 34.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.costco.com/tide',
        imageUrl: 'https://placehold.co/200x200/B5B3E1/2D2D2D?text=Tide',
      },
      {
        retailer: 'samsclub',
        title: 'Tide PODS Original',
        brand: 'Tide',
        size: '120 count',
        price: 28.98,
        stockStatus: 'in-stock',
        productUrl: 'https://www.samsclub.com/tide',
        imageUrl: 'https://placehold.co/200x200/B5B3E1/2D2D2D?text=Tide',
      },
    ],
  },
  {
    name: 'toilet paper',
    category: 'household',
    variants: [
      {
        retailer: 'walmart',
        title: 'Charmin Ultra Soft Toilet Paper',
        brand: 'Charmin',
        size: '18 mega rolls',
        price: 21.98,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walmart.com/tp',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/B5B3E1?text=TP',
      },
      {
        retailer: 'walgreens',
        title: 'Scott Comfort Plus Toilet Paper',
        brand: 'Scott',
        size: '12 rolls',
        price: 14.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.walgreens.com/tp',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/B5B3E1?text=TP',
      },
      {
        retailer: 'marianos',
        title: 'Quilted Northern Ultra Plush',
        brand: 'Quilted Northern',
        size: '16 mega rolls',
        price: 19.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.marianos.com/tp',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/B5B3E1?text=TP',
      },
      {
        retailer: 'costco',
        title: 'Kirkland Signature Bath Tissue',
        brand: 'Kirkland',
        size: '30 rolls',
        price: 24.99,
        stockStatus: 'in-stock',
        productUrl: 'https://www.costco.com/tp',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/B5B3E1?text=TP',
      },
      {
        retailer: 'samsclub',
        title: 'Member\'s Mark Bath Tissue',
        brand: 'Member\'s Mark',
        size: '45 rolls',
        price: 27.98,
        stockStatus: 'in-stock',
        productUrl: 'https://www.samsclub.com/tp',
        imageUrl: 'https://placehold.co/200x200/E8F0D5/B5B3E1?text=TP',
      },
    ],
  },
];

// Helper function to search products by name
export function searchProductsByName(searchTerm: string): MockProduct | undefined {
  const normalizedSearch = searchTerm.toLowerCase().trim();
  return mockProducts.find(product => 
    product.name.toLowerCase().includes(normalizedSearch) || 
    normalizedSearch.includes(product.name.toLowerCase())
  );
}

// Helper function to get all products for a retailer
export function getProductsByRetailer(retailer: Retailer): RetailerProduct[] {
  return mockProducts.flatMap(product => 
    product.variants
      .filter(variant => variant.retailer === retailer)
      .map(variant => ({
        ...variant,
        retailer: variant.retailer as Retailer,
      }))
  );
}

// Helper function to get all products
export function getAllProducts(): RetailerProduct[] {
  return mockProducts.flatMap(product => 
    product.variants.map(variant => ({
      ...variant,
      retailer: variant.retailer as Retailer,
    }))
  );
}

